### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by hyw-freeway** [XuhuiM/PPINN#1]
你好。
 我是一名来自中国的研究生。最近，我阅读了您的论文PPINN: Parareal physics-informed neural network for time-dependent pde。我有几个疑问，如果您能抽出宝贵的时间来解释，我将不胜感激。
对于pinn模型，用训练数据训练后，是否需要将数据分为测试数据和验证数据来验证模型的有效性?在您的论文中，训练的模型数据似乎直接与其他解析方程的结果进行了比较。
再次感谢大家的聆听。如果你能回答我的问题，我将非常感激。祝你生活幸福!

**Comment by XuhuiM** [comment]
PPINN is developed for solving forward PDE problems in parallel. For forward problems, we only have training data on boundary/initial conditions. We compare the PINN predictions with the results from numerical solvers after training. We do not use validation data in the forward problems.

**Comment by hyw-freeway** [comment]
Thank you very much for your answer, which is very useful to me! Thank you, have a nice life!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XuhuiM/PPINN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月17日(星期五) 上午8:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XuhuiM/PPINN] 问题 (Issue #1)





 
PPINN is developed for solving forward PDE problems in parallel. For forward problems, we only have training data on boundary/initial conditions. We compare the PINN predictions with the results from numerical solvers after training. We do not use validation data in the forward problems.

**Comment by hyw-freeway** [comment]
I'm sorry to bother you again. What you mean by "we only have training data on boundary/initial conditions" is that the input dataset is the boundary conditions and the initial data at the time of t=0, not  include the y value of the whole time T, right? The y value of each time step trained by the neural network is compared with the y value of the standard solution of the corresponding time step to evaluate the performance of the model.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "胡玉炜"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月17日(星期五) 上午9:24
***@***.***&gt;;

主题:&nbsp;回复： [XuhuiM/PPINN] 问题 (Issue #1)





Thank you very much for your answer, which is very useful to me! Thank you, have a nice life!


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "XuhuiM/PPINN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月17日(星期五) 上午8:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XuhuiM/PPINN] 问题 (Issue #1)





 
PPINN is developed for solving forward PDE problems in parallel. For forward problems, we only have training data on boundary/initial conditions. We compare the PINN predictions with the results from numerical solvers after training. We do not use validation data in the forward problems.

**Comment by XuhuiM** [comment]
Yes.
